# Generated by Django 6.0.3 on 2026-06-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantworkinghours',
            options={'ordering': ['weekday']},
        ),
        migrations.AddField(
            model_name='restaurantworkinghours',
            name='closes_next_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantworkinghours',
            name='is_day_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='restaurantworkinghours',
            constraint=models.UniqueConstraint(fields=('restaurant', 'weekday'), name='unique_working_hours_per_day'),
        ),
    ]
