# Generated by Django 6.0.3 on 2026-06-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurantworkinghours_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='reservation_duration',
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='restaurantworkinghours',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')]),
        ),
    ]
