# Generated by Django 6.0.3 on 2026-07-11 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_reservation_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Reason')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='restaurants.restaurant')),
            ],
        ),
    ]
