# Generated by Django 6.0.3 on 2026-07-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurantclosure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantworkinghours',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantworkinghours',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
