# Generated by Django 6.0.3 on 2026-06-28 11:09

from django.db import migrations
from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        BtreeGistExtension(),
    ]
