# Generated by Django 6.0.3 on 2026-06-14 12:45

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guests',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='restaurants.restaurant'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['restaurant', 'start_time'], name='reservation_restaur_0e461e_idx'),
        ),
    ]
